In [20]:
import numpy as np
import pandas as pd

In [21]:
df = pd.read_excel("../data/raw/Payment_System_Indicators.xlsx", header = None)

C:\Users\Sahil\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [22]:
df.head(n=25)

,0,1,2,3,4,5,6,7,8,9,...,132,133,134,135,136,137,138,139,140,141
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Payment System Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Month/Year,A. Settlement Systems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Financial Market Infrastructures (FMIs),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,1 CCIL Operated Systems (1.1 to 1.3),NaN,1.1 Govt. Securities Clearing (1.1.1 to 1.1.3),NaN,1.1.1 Outright,NaN,1.1.2 Repo,NaN,...,3.2 White Label ATMs $,NaN,4 Number of Micro ATMs @,NaN,5 Number of PoS Terminals,NaN,6 Bharat QR @,NaN,7 UPI QR *,NaN
6,NaN,NaN,Volume (Lakh),Value( Rupees Crores ),Volume (Lakh),Value( Rupees Crores ),Volume (Lakh),Value( Rupees Crores ),Volume (Lakh),Value( Rupees Crores ),...,Volume (Lakh),Value( Rupees Crores ),Volume (Lakh),Value( Rupees Crores ),Volume (Lakh),Value( Rupees Crores ),Volume (Lakh),Value( Rupees Crores ),Volume (Lakh),Value( Rupees Crores )
7,NaN,Mar-2026,4.438,30819254.479,1.512,16548550.465,0.837,1200663.001,0.459,6833924.214,...,0.378,-,13.899,-,117.694,-,56.33,-,7612.174,-
8,NaN,Feb-2026,4.371,29363077.938,1.618,17227563.99,0.939,1339432.608,0.457,6696114.632,...,0.378,-,13.895,-,116.649,-,58.974,-,7542.037,-
9,NaN,Jan-2026,4.34982,32155353.739944,1.60677,18709470.219944,0.89591,1235355.879944,0.46317,7775967.59,...,0.37906,-,13.91526,-,115.4521,-,58.43742,-,7383.8038,7574.12462
10,NaN,Dec-2025,5.06995,34813890.97045,1.70905,20459215.74445,0.9377,1358771.764451,0.5142,9176296.78,...,0.3733,0,14.14547,0,114.74672,0,58.9022,0,7313.65285,7503.95203
11,NaN,Nov-2025,4.07934,28209255.757823,1.53112,17161812.807823,0.87911,1226375.205823,0.44072,7838568.802,...,0.3723,-,14.27193,-,112.53425,-,59.52557,-,7281.995555,7470.833525
12,NaN,Oct-2025,4.249655,30434601.267631,1.63321,18365110.727631,0.94771,1439939.427631,0.4559,8365989.75,...,0.36725,-,14.64566,-,123.08241,-,60.47707,-,7174.33868,7375.03991
13,NaN,Sep-2025,4.94887,30270023.371588,1.75093,18003263.271589,1.0396,1499643.171589,0.47642,7926471.1,...,0.36532,-,14.59945,-,121.16102,-,60.70528,-,7089.7474,7288.69994
14,NaN,Aug-2025,4.28444,28151945.628472,1.49547,16614169.828472,0.80862,1240950.828472,0.47016,7489699.5,...,0.36207,-,14.71422,-,119.64613,-,65.73082,-,6977.47231,7180.04966
15,NaN,Jul-2025,5.20543,32781615.507044,1.63165,19293299.030619,0.84171,1274228.320619,0.5451,8664018.16,...,0.35927,-,14.66668,-,119.1308,-,66.41351,-,6880.30939,7083.01353
16,NaN,Jun-2025,5.29633,30959727.204822,1.76906,17946467.824822,1.04741,1611828.514822,0.50694,7894090.51,...,0.35746,-,14.59218,-,117.82954,-,66.99048,-,6781.60811,6983.52928
17,NaN,May-2025,5.48351,29656042.05,1.93874,17500816.49,1.27706,1875057,0.45304,7645792.49,...,0.3559,-,14.78043,-,115.81161,-,66.42075,-,6697.29906,6896.88114
18,NaN,Apr-2025,5.066205,29399813.743751,1.88789,16657576.463751,1.30418,2017823.14375,0.38304,7078422.37,...,0.36198,-,14.73668,-,112.83266,-,66.63778,-,6623.84943,6820.60686
19,NaN,Mar-2025,4.36161,27936158.351369,1.33182,15356047.801369,0.76179,1297378.021369,0.3561,6589738.03,...,0.36216,-,14.81883,-,110.98051,-,67.18039,-,6579.29517,6774.83375
20,NaN,Feb-2025,3.72274,25171732.919768,1.15725,14137926.109768,0.62616,1088597.629768,0.3292,5916603.13,...,0.36016,-,14.67966,-,107.17514,-,65.48149,-,6496.9128,6686.82472
21,NaN,Jan-2025,4.88137,30296789.631096,1.76767,17807347.241096,1.10389,1627265.091096,0.41265,7288494.35,...,0.35801,-,14.73899,-,103.5273,-,64.43092,-,6401.64702,6586.91536
22,NaN,Dec-2024,3.776745,27448819.717569,1.48975,16506679.857569,0.84363,1348781.687569,0.40736,6377679.12,...,0.35853,-,14.76237,-,100.00549,-,63.82626,-,6335.29503,6516.43703
23,NaN,Nov-2024,2.61147,20592498.474564,1.09836,13954925.394564,0.54225,847484.694564,0.35492,5366007.15,...,0.35301,-,14.51783,-,96.90872,-,63.59691,-,6261.79913,6439.37438
24,NaN,Oct-2024,3.59073,25730863.762922,1.68925,16664119.967922,1.04383,1626397.357922,0.41404,6573747.91,...,0.35028,-,14.50704,-,95.09265,-,64.31243,-,6168.51592,6344.98479

In [23]:
for i, col in enumerate(df.iloc[5]):
    print(i, col)

0 nan
1 nan
2 1   CCIL Operated Systems (1.1 to 1.3)
3 nan
4 1.1 Govt. Securities Clearing (1.1.1 to 1.1.3)
5 nan
6 1.1.1 Outright
7 nan
8 1.1.2 Repo
9 nan
10 1.1.3 Tri-party Repo
11 nan
12 1.2 Forex Clearing
13 nan
14 1.3 Rupee Derivatives @
15 nan
16 1 Credit Transfers - RTGS (1.1 to 1.2)
17 nan
18 1.1 Customer Transactions
19 nan
20 1.2 Interbank Transactions
21 nan
22 2 Credit Transfers - Retail (2.1 to 2.7)
23 nan
24 2.1 AePS (Fund Transfers) @
25 nan
26 2.2 APBS $
27 nan
28 2.3 ECS Cr
29 nan
30 2.4 IMPS
31 nan
32 2.5 NACH Cr $
33 nan
34 2.6 NEFT
35 nan
36 2.7 UPI @
37 nan
38 2.7.1 of which USSD @
39 nan
40 3 Debit Transfers and Direct Debits (3.1 to 3.4)
41 nan
42 3.1 BHIM Aadhaar Pay @
43 nan
44 3.2 ECS Dr
45 nan
46 3.3 NACH Dr $
47 nan
48 3.4 NETC (linked to bank account) @
49 nan
50 4 Card Payments (4.1 to 4.2)
51 nan
52 4.1 Credit Cards (4.1.1 to 4.1.2)
53 nan
54 4.1.1 PoS based $
55 nan
56 4.1.2 Others $
57 nan
58 4.2 Debit Cards (4.2.1 to 4.2.1 )
59 nan
60 4.2.1 PoS based $
61 nan
62 4.2.2 Others $
63 nan
64 5 Prepaid Payment Instruments (5.1 to 5.2)
65 nan
66 5.1 Wallets
67 nan
68 5.2 Cards (5.2.1 to 5.2.2)
69 nan
70 5.2.1 PoS based $
71 nan
72 5.2.2 Others $
73 nan
74 6 Paper-based Instruments (6.1 to 6.2)
75 nan
76 6.1 CTS (NPCI Managed)
77 nan
78 6.2 Others
79 nan
80 Total - Retail Payments (2+3+4+5+6)
81 nan
82 Total Payments (1+2+3+4+5+6)
83 nan
84 Total Digital Payments (1+2+3+4+5)
85 nan
86 1 Mobile Payments (mobile app based) (1.1 to 1.2)
87 nan
88 1.1 Intra-bank $
89 nan
90 1.2 Inter-bank $
91 nan
92 2 Internet Payments (Netbanking / Internet Browser Based) @ (2.1 to 2.2)
93 nan
94 2.1 Intra-bank @
95 nan
96 2.2 Inter-bank @
97 nan
98 3 Cash Withdrawal at ATMs $ (3.1 to 3.3)
99 nan
100 3.1 Using Credit Cards $
101 nan
102 3.2 Using Debit Cards $
103 nan
104 3.3 Using Pre-paid Cards $
105 nan
106 4 Cash Withdrawal at PoS $ (4.1 to 4.2)
107 nan
108 4.1 Using Debit Cards $
109 nan
110 4.2 Using Pre-paid Cards $
111 nan
112 5   Cash Withrawal at Micro ATMs @
113 nan
114 5.1 AePS @
115 nan
116 1 Number of Cards (1.1 to 1.2)
117 nan
118 1.1 Credit Cards
119 nan
120 1.2 Debit Cards
121 nan
122 2 Number of PPIs @ (2.1 to 2.2)
123 nan
124 2.1 Wallets @
125 nan
126 2.2 Cards @
127 nan
128 3 Number of ATMs (3.1 to 3.2)
129 nan
130 3.1 Bank owned ATMs $
131 nan
132 3.2 White Label ATMs $
133 nan
134 4   Number of Micro ATMs @
135 nan
136 5   Number of PoS Terminals
137 nan
138 6   Bharat QR @
139 nan
140 7 UPI QR *
141 nan

In [24]:
for i, col in enumerate(df.iloc[6]):
    print(i, col)

0 nan
1 nan
2 Volume (Lakh)
3 Value( Rupees Crores )
4 Volume (Lakh)
5 Value( Rupees Crores )
6 Volume (Lakh)
7 Value( Rupees Crores )
8 Volume (Lakh)
9 Value( Rupees Crores )
10 Volume (Lakh)
11 Value( Rupees Crores )
12 Volume (Lakh)
13 Value( Rupees Crores )
14 Volume (Lakh)
15 Value( Rupees Crores )
16 Volume (Lakh)
17 Value( Rupees Crores )
18 Volume (Lakh)
19 Value( Rupees Crores )
20 Volume (Lakh)
21 Value( Rupees Crores )
22 Volume (Lakh)
23 Value( Rupees Crores )
24 Volume (Lakh)
25 Value( Rupees Crores )
26 Volume (Lakh)
27 Value( Rupees Crores )
28 Volume (Lakh)
29 Value( Rupees Crores )
30 Volume (Lakh)
31 Value( Rupees Crores )
32 Volume (Lakh)
33 Value( Rupees Crores )
34 Volume (Lakh)
35 Value( Rupees Crores )
36 Volume (Lakh)
37 Value( Rupees Crores )
38 Volume (Lakh)
39 Value( Rupees Crores )
40 Volume (Lakh)
41 Value( Rupees Crores )
42 Volume (Lakh)
43 Value( Rupees Crores )
44 Volume (Lakh)
45 Value( Rupees Crores )
46 Volume (Lakh)
47 Value( Rupees Crores )
48 Volume (Lakh)
49 Value( Rupees Crores )
50 Volume (Lakh)
51 Value( Rupees Crores )
52 Volume (Lakh)
53 Value( Rupees Crores )
54 Volume (Lakh)
55 Value( Rupees Crores )
56 Volume (Lakh)
57 Value( Rupees Crores )
58 Volume (Lakh)
59 Value( Rupees Crores )
60 Volume (Lakh)
61 Value( Rupees Crores )
62 Volume (Lakh)
63 Value( Rupees Crores )
64 Volume (Lakh)
65 Value( Rupees Crores )
66 Volume (Lakh)
67 Value( Rupees Crores )
68 Volume (Lakh)
69 Value( Rupees Crores )
70 Volume (Lakh)
71 Value( Rupees Crores )
72 Volume (Lakh)
73 Value( Rupees Crores )
74 Volume (Lakh)
75 Value( Rupees Crores )
76 Volume (Lakh)
77 Value( Rupees Crores )
78 Volume (Lakh)
79 Value( Rupees Crores )
80 Volume (Lakh)
81 Value( Rupees Crores )
82 Volume (Lakh)
83 Value( Rupees Crores )
84 Volume (Lakh)
85 Value( Rupees Crores )
86 Volume (Lakh)
87 Value( Rupees Crores )
88 Volume (Lakh)
89 Value( Rupees Crores )
90 Volume (Lakh)
91 Value( Rupees Crores )
92 Volume (Lakh)
93 Value( Rupees Crores )
94 Volume (Lakh)
95 Value( Rupees Crores )
96 Volume (Lakh)
97 Value( Rupees Crores )
98 Volume (Lakh)
99 Value( Rupees Crores )
100 Volume (Lakh)
101 Value( Rupees Crores )
102 Volume (Lakh)
103 Value( Rupees Crores )
104 Volume (Lakh)
105 Value( Rupees Crores )
106 Volume (Lakh)
107 Value( Rupees Crores )
108 Volume (Lakh)
109 Value( Rupees Crores )
110 Volume (Lakh)
111 Value( Rupees Crores )
112 Volume (Lakh)
113 Value( Rupees Crores )
114 Volume (Lakh)
115 Value( Rupees Crores )
116 Volume (Lakh)
117 Value( Rupees Crores )
118 Volume (Lakh)
119 Value( Rupees Crores )
120 Volume (Lakh)
121 Value( Rupees Crores )
122 Volume (Lakh)
123 Value( Rupees Crores )
124 Volume (Lakh)
125 Value( Rupees Crores )
126 Volume (Lakh)
127 Value( Rupees Crores )
128 Volume (Lakh)
129 Value( Rupees Crores )
130 Volume (Lakh)
131 Value( Rupees Crores )
132 Volume (Lakh)
133 Value( Rupees Crores )
134 Volume (Lakh)
135 Value( Rupees Crores )
136 Volume (Lakh)
137 Value( Rupees Crores )
138 Volume (Lakh)
139 Value( Rupees Crores )
140 Volume (Lakh)
141 Value( Rupees Crores )

In [69]:
payments = pd.DataFrame()

payments['Month'] = df.iloc[7:, 1]

payments['UPI_Volume_inlakhs'] = df.iloc[7:, 36]
payments['UPI_Value_inCr'] = df.iloc[7:, 37]

payments['Credit_Volume_inlakhs'] = df.iloc[7:, 52]
payments['Credit_Value_inCr'] = df.iloc[7:, 53]

payments['Debit_Volume_inlakhs'] = df.iloc[7:, 58]
payments['Debit_Value_inCr'] = df.iloc[7:, 59]

payments['ATM_Debit_Volume_inlakhs'] = df.iloc[7:, 102]
payments['ATM_Debit_Value_inCr'] = df.iloc[7:, 103]

payments.head()

,Month,UPI_Volume_inlakhs,UPI_Value_inCr,Credit_Volume_inlakhs,Credit_Value_inCr,Debit_Volume_inlakhs,Debit_Value_inCr,ATM_Debit_Volume_inlakhs,ATM_Debit_Value_inCr
7,Mar-2026,226411.08,2952542.03,5774.765,219494.691,1013.174,37948.392,4439.993,248419.035
8,Feb-2026,203941.84,2684229.3,4937.955,177291.983,917.122,33134.625,4145.117,230241.73
9,Jan-2026,217034.45,2833481.26,5397.11275,199084.866031,1018.29499,37956.691165,4412.00393,239172.025352
10,Dec-2025,216346.68,2796712.71,5398.34125,204686.606452,1049.2403,37274.380087,4444.01793,238924.8011
11,Nov-2025,204669.79,2631632.64,5029.84178,188799.00989,1012.11314,34143.386569,4380.22645,234054.556201

In [70]:
payments.tail()

,Month,UPI_Volume_inlakhs,UPI_Value_inCr,Credit_Volume_inlakhs,Credit_Value_inCr,Debit_Volume_inlakhs,Debit_Value_inCr,ATM_Debit_Volume_inlakhs,ATM_Debit_Value_inCr
83,Nov-2019,12187.70742,189229.089108,1762.12447,60130.248377,4180.838165,58208.685669,6236.886457,281337.849821
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,@: New inclusion w.e.f. November 2019\n $ : I...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,1. Data is provisional.\n2. ECS (Debit and Cre...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
payments[payments['Month'].isna()]

,Month,UPI_Volume_inlakhs,UPI_Value_inCr,Credit_Volume_inlakhs,Credit_Value_inCr,Debit_Volume_inlakhs,Debit_Value_inCr,ATM_Debit_Volume_inlakhs,ATM_Debit_Value_inCr
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
payments = payments.iloc[:77]

In [73]:
payments = payments.reset_index(drop='true')

In [74]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Month                     77 non-null     object
 1   UPI_Volume_inlakhs        77 non-null     object
 2   UPI_Value_inCr            77 non-null     object
 3   Credit_Volume_inlakhs     77 non-null     object
 4   Credit_Value_inCr         77 non-null     object
 5   Debit_Volume_inlakhs      77 non-null     object
 6   Debit_Value_inCr          77 non-null     object
 7   ATM_Debit_Volume_inlakhs  77 non-null     object
 8   ATM_Debit_Value_inCr      77 non-null     object
dtypes: object(9)
memory usage: 5.5+ KB

In [75]:
payments['Month'].head()

0    Mar-2026
1    Feb-2026
2    Jan-2026
3    Dec-2025
4    Nov-2025
Name: Month, dtype: object

In [76]:
payments['Month'].tail()

72    Mar-2020
73    Feb-2020
74    Jan-2020
75    Dec-2019
76    Nov-2019
Name: Month, dtype: object

In [77]:
payments['Month'] = pd.to_datetime(payments['Month'],  format='%b-%Y')

In [78]:
payments = payments.sort_values('Month')
payments = payments.reset_index(drop='true')

In [79]:
payments = payments.replace('-', pd.NA)

numeric_cols = payments.columns.drop('Month')

payments[numeric_cols] = payments[numeric_cols].apply(
    pd.to_numeric,
    errors='coerce'
)

In [80]:
payments.dtypes

Month                       datetime64[ns]
UPI_Volume_inlakhs                 float64
UPI_Value_inCr                     float64
Credit_Volume_inlakhs              float64
Credit_Value_inCr                  float64
Debit_Volume_inlakhs               float64
Debit_Value_inCr                   float64
ATM_Debit_Volume_inlakhs           float64
ATM_Debit_Value_inCr               float64
dtype: object

In [81]:
payments.isna().sum()

Month                       0
UPI_Volume_inlakhs          0
UPI_Value_inCr              0
Credit_Volume_inlakhs       0
Credit_Value_inCr           0
Debit_Volume_inlakhs        0
Debit_Value_inCr            0
ATM_Debit_Volume_inlakhs    0
ATM_Debit_Value_inCr        0
dtype: int64

In [82]:
payments.describe()

,UPI_Volume_inlakhs,UPI_Value_inCr,Credit_Volume_inlakhs,Credit_Value_inCr,Debit_Volume_inlakhs,Debit_Value_inCr,ATM_Debit_Volume_inlakhs,ATM_Debit_Value_inCr
count,77.000000,7.700000e+01,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000
mean,93119.256524,1.362945e+06,2884.561451,125224.263532,2421.760606,51116.980597,5253.102946,257195.662710
std,66881.578168,8.458072e+05,1252.618155,54142.394937,1049.750962,11328.749950,639.591396,25147.816963
min,9995.743760,1.511407e+05,768.532330,20764.769499,917.122000,23250.482568,2935.257920,128559.710996
25%,28075.160000,5.473732e+05,1884.239840,72318.816897,1423.935480,41258.862535,4734.614800,243929.532209
50%,78288.950000,1.281971e+06,2556.465050,127682.395559,2382.495730,51049.346831,5428.470350,261123.847239
75%,149630.470000,2.063995e+06,3900.493240,169298.163540,3315.647750,61087.438080,5685.103990,275032.398845
max,226411.080000,2.952542e+06,5774.765000,219494.691000,4500.845880,76470.509905,6495.686000,294174.321869

In [84]:
payments.to_csv("../data/processed/payments_master.csv", index=False)

# Data Audit Summary

## Dataset
RBI Payment System Indicators

## Time Period

First Month:
November 2019

Last Month:
March 2026

Total Observations:
77 Monthly Records

## Metrics Extracted

- UPI Transaction Volume
- UPI Transaction Value
- Credit Card Transaction Volume
- Credit Card Transaction Value
- Debit Card Transaction Volume
- Debit Card Transaction Value
- ATM Withdrawals using Debit Cards (Volume & Value)

## Cleaning Performed

- Removed footer rows and notes
- Converted Month to datetime format
- Replaced '-' values with missing values
- Converted transaction metrics to numeric format
- Sorted data chronologically

## Initial Observation

UPI transaction volume is substantially larger than card transaction volume throughout the available period, indicating its dominant role in India's digital payments ecosystem.

## Units

Transaction Volume:
- Measured in Lakh Transactions

Transaction Value:
- Measured in ₹ Crore